"""The successor grammar: 0, S(0), S(S(0)), …  (GIN-DEF-009 … GIN-DEF-012).

The natural numbers are generated by the structural grammar

    N  →  0  |  S(N)

and arithmetic is defined by primitive recursion on that grammar.  This module
makes the recursion explicit and *counts rule applications*, so that one can see
that unary (Peano) arithmetic costs time proportional to the *values* — that is,
exponential in the length of a binary numeral (GIN-PROP-003).

It also formalizes the segment notation ``a{I}b`` (for example ``0{1,2,3}4``)
proposed in the research mandate (GIN-DEF-012), and provides small transition
systems for fixed-point exercises.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Callable

from .cost import Cost, charge


# ---------------------------------------------------------------------------
# Peano terms
# ---------------------------------------------------------------------------
def term(n: int) -> str:
    """The successor term for n: term(3) == 'S(S(S(0)))'."""
    if n < 0:
        raise ValueError("Peano terms denote natural numbers")
    return "S(" * n + "0" + ")" * n


def parse_term(t: str) -> int:
    """Inverse of :func:`term`, validating the grammar N → 0 | S(N)."""
    t = t.replace(" ", "")
    m = re.fullmatch(r"(S\()*0(\))*", t)
    if not m:
        raise ValueError(f"{t!r} is not a successor term")
    k = t.count("S(")
    if t.count(")") != k:
        raise ValueError(f"{t!r} has unbalanced parentheses")
    return k


# Primitive-recursive arithmetic with rule counting. Each function mirrors the
# defining equations exactly; ``cost`` is charged one ``rule`` per equation used.
#
#   add(m, 0) = m                    add(m, S n) = S(add(m, n))
#   mul(m, 0) = 0                    mul(m, S n) = add(mul(m, n), m)
#   pow(m, 0) = S 0                  pow(m, S n) = mul(pow(m, n), m)
#   pred(0) = 0                      pred(S n) = n
#   monus(m, 0) = m                  monus(m, S n) = pred(monus(m, n))
#
# Values are stored as Python ints for speed; the *number of rule applications*
# is exactly what unfolding the terms would cost.

def add(m: int, n: int, cost: Cost | None = None) -> int:
    """Peano addition. Uses exactly n + 1 rule applications (GIN-PROP-003)."""
    charge(cost, "rule", n + 1)
    charge(cost, "S", n)
    return m + n


def mul(m: int, n: int, cost: Cost | None = None) -> int:
    """Peano multiplication: n + 1 rules of mul, plus the additions they call."""
    acc = 0
    charge(cost, "rule")                # mul(m, 0) = 0
    for _ in range(n):
        charge(cost, "rule")            # mul(m, S k) = add(mul(m, k), m)
        acc = add(acc, m, cost)
    return acc


def power(m: int, n: int, cost: Cost | None = None) -> int:
    acc = 1
    charge(cost, "rule")
    for _ in range(n):
        charge(cost, "rule")
        acc = mul(acc, m, cost)
    return acc


def pred(n: int, cost: Cost | None = None) -> int:
    charge(cost, "rule")
    return n - 1 if n > 0 else 0


def monus(m: int, n: int, cost: Cost | None = None) -> int:
    """Truncated subtraction m ∸ n = max(m − n, 0): the total function that N offers.

    Note that monus is total but is *not* the converse of addition: 0 ∸ 1 = 0 while
    no c in N satisfies 1 + c = 0 (GIN-REI-003).
    """
    charge(cost, "rule")
    acc = m
    for _ in range(n):
        charge(cost, "rule")
        acc = pred(acc, cost)
    return acc


# ---------------------------------------------------------------------------
# Genuine term rewriting (witnesses the rule counts above on small inputs)
# ---------------------------------------------------------------------------
# A term is "0", ("S", t), ("add", t, u), ("mul", t, u).  rewrite() applies the
# defining equations one at a time (leftmost-outermost redex first) and records
# every step, so that the counts charged by add() and mul() can be checked
# against an actual derivation rather than a formula.
def num(n: int):
    t = "0"
    for _ in range(n):
        t = ("S", t)
    return t


def show(t) -> str:
    if t == "0":
        return "0"
    if t[0] == "S":
        k, u = 0, t
        while u != "0" and u[0] == "S":
            k, u = k + 1, u[1]
        return ("S" * k + "0") if u == "0" else "S" * k + "(" + show(u) + ")"
    return f"{t[0]}({show(t[1])}, {show(t[2])})"


def _step(t):
    """One rewrite step at the leftmost-outermost redex; returns (term, rule) or None."""
    if t == "0":
        return None
    if t[0] == "S":
        r = _step(t[1])
        return None if r is None else (("S", r[0]), r[1])
    op, a, b = t
    if op == "add":
        if b == "0":
            return a, "add(m, 0) = m"
        if b[0] == "S":
            return ("S", ("add", a, b[1])), "add(m, S n) = S(add(m, n))"
    if op == "mul":
        if b == "0":
            return "0", "mul(m, 0) = 0"
        if b[0] == "S":
            return ("add", ("mul", a, b[1]), a), "mul(m, S n) = add(mul(m, n), m)"
    for i in (1, 2):                       # no rule applies at the root: rewrite inside, left first
        r = _step(t[i])
        if r is not None:
            new = list(t)
            new[i] = r[0]
            return tuple(new), r[1]
    return None


def rewrite(t, max_steps: int = 100_000) -> tuple[object, list[tuple[str, str]]]:
    """Normalize a term by the defining equations; return (normal form, [(rule, term after)])."""
    trace = []
    while len(trace) < max_steps:
        r = _step(t)
        if r is None:
            return t, trace
        t = r[0]
        trace.append((r[1], show(t)))
    raise RuntimeError("no normal form within max_steps")


def church(n: int) -> Callable[[Callable], Callable]:
    """Church numeral: n ↦ (f ↦ f∘…∘f, n times). Number as the grammar of iteration."""
    def numeral(f):
        def iterate(x):
            for _ in range(n):
                x = f(x)
            return x
        return iterate
    return numeral


def unchurch(c) -> int:
    return c(lambda k: k + 1)(0)


# ---------------------------------------------------------------------------
# Segments and the a{I}b notation
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Segment:
    """The segment of the successor chain from a to b (a < b), as a transition system.

    Elements: a, a+1, …, b.  Moves: S (successor) defined on a … b−1, and its converse
    P (predecessor) defined on a+1 … b.  The *boundary* is {a, b}; the *interior* is
    {a+1, …, b−1}; each interior point has both moves defined, each boundary point
    exactly one.
    """

    a: int
    b: int

    def __post_init__(self):
        if not self.a < self.b:
            raise ValueError("a segment needs a < b")

    @property
    def elements(self) -> list[int]:
        return list(range(self.a, self.b + 1))

    @property
    def interior(self) -> list[int]:
        return list(range(self.a + 1, self.b))

    @property
    def boundary(self) -> tuple[int, int]:
        return (self.a, self.b)

    def admissible(self, x: int, move: str) -> bool:
        if move == "S":
            return self.a <= x < self.b
        if move == "P":
            return self.a < x <= self.b
        raise ValueError(move)

    def run(self, x: int, word: str) -> int | None:
        """Apply a word over {S, P}; None if some step is inadmissible."""
        for mv in word:
            if not self.admissible(x, mv):
                return None
            x = x + 1 if mv == "S" else x - 1
        return x

    def notation(self) -> str:
        return f"{self.a}{{{','.join(map(str, self.interior))}}}{self.b}"

    def transitions(self) -> list[tuple[int, str, int]]:
        return [(x, "S", x + 1) for x in range(self.a, self.b)]


_SEG = re.compile(r"\s*(-?\d+)\s*\{\s*((?:-?\d+\s*(?:,\s*-?\d+\s*)*)?)\}\s*(-?\d+)\s*$")


@dataclass
class SegmentParse:
    ok: bool
    segment: Segment | None
    diagnosis: str


def parse_segment(text: str) -> SegmentParse:
    """Parse and *validate* the notation a{i₁,…,i_k}b (GIN-DEF-012).

    Well-formed iff a < b and {i₁,…,i_k} is exactly {a+1,…,b−1} listed in increasing
    order. Every failure names the violated condition.
    """
    m = _SEG.match(text)
    if not m:
        return SegmentParse(False, None, "syntax: expected the form a{i1,...,ik}b")
    a, b = int(m.group(1)), int(m.group(3))
    inner = [int(x) for x in m.group(2).split(",")] if m.group(2).strip() else []
    if not a < b:
        return SegmentParse(False, None, f"boundary: need a < b, got {a} ≥ {b}")
    expected = list(range(a + 1, b))
    if inner == expected:
        return SegmentParse(True, Segment(a, b), f"segment from {a} to {b}: {b - a} successor transition{'s' if b - a != 1 else ''}, interior of size {b - a - 1}")
    missing = sorted(set(expected) - set(inner))
    extra = sorted(set(inner) - set(expected))
    if missing or extra:
        parts = []
        if missing:
            parts.append(f"interior misses {missing}")
        if extra:
            parts.append(f"{extra} lie outside the open interval ({a}, {b})")
        return SegmentParse(False, None, "interior: " + "; ".join(parts))
    return SegmentParse(False, None, "order: interior must be listed in successor order")


# ---------------------------------------------------------------------------
# Fixed points of maps on finite sets of numbers
# ---------------------------------------------------------------------------
def fixed_points(f: Callable[[int], int], domain: range) -> list[int]:
    return [x for x in domain if f(x) == x]


def orbit(f: Callable[[int], int], x: int, max_steps: int = 10_000) -> tuple[list[int], int | None]:
    """Iterate f from x until a value repeats. Returns (trajectory, index where the cycle starts)."""
    seen: dict[int, int] = {}
    traj: list[int] = []
    while x not in seen and len(traj) < max_steps:
        seen[x] = len(traj)
        traj.append(x)
        x = f(x)
    return traj, seen.get(x)
