// Print edition: render dist/print.html (generated by tools/build.mjs from the
// same canonical sources as the website) to a PDF with headless Chromium, then
// inspect the result and publish it under site/downloads with a manifest.
//
//   npm run build && npm run pdf && npm run build   (the second build picks up the manifest)
//
// Release checks performed here (any failure exits non-zero and publishes nothing):
//   * no element is wider than the A4 text block (it would be clipped in print);
//   * the file is a PDF, of plausible size, and pdfinfo reports its page count;
//   * every chapter title and the bibliography appear in the extracted text;
//   * the extracted text contains no U+FFFD replacement characters;
//   * every font in the PDF is embedded (pdffonts);
//   * the content version printed in the PDF equals the sources' content version.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import { chromium } from "playwright-core";
import { serve } from "./serve.mjs";

const FILE = "grammar-in-numbers.pdf";
const dist = path.resolve("dist");
const out = path.join(dist, FILE);
const build = JSON.parse(fs.readFileSync(path.join(dist, "build.json"), "utf8"));
const book = JSON.parse(fs.readFileSync(path.resolve("content", "book.json"), "utf8"));
const fail = (msg) => { console.error(`PDF release check failed: ${msg}`); process.exit(1); };

const srv = await serve(0);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const page = await browser.newPage();
await page.goto(`http://127.0.0.1:${srv.address().port}/print.html`, { waitUntil: "networkidle" });
await page.emulateMedia({ media: "print" });
await page.evaluate(() => document.fonts.ready);
// A4 text block: 210 mm − 2 × 20 mm = 170 mm ≈ 642 CSS px.
await page.setViewportSize({ width: 642, height: 900 });
const wide = await page.evaluate(() => [...document.querySelectorAll(".katex-display > .katex, table, pre, img, svg")]
  .filter((e) => e.scrollWidth > (e.closest(".equation, .table-wrap, figure, .env, article, main") || document.body).clientWidth + 1)
  .map((e) => `${e.tagName}: ${(e.textContent || "").replace(/\s+/g, " ").slice(0, 70)}`));
if (wide.length) { console.error(`${wide.length} element(s) wider than the print text block:\n  ${wide.join("\n  ")}`); await browser.close(); srv.close(); process.exit(1); }
await page.pdf({ path: out, format: "A4", printBackground: false, displayHeaderFooter: true, outline: true, tagged: true,
  headerTemplate: "<span></span>",
  footerTemplate: `<div style="font-size:7.5px;width:100%;text-align:center;color:#666;font-family:serif">${book.title} — Abed Kadaan — ${book.edition} — content ${build.content_version} — <span class="pageNumber"></span> / <span class="totalPages"></span></div>`,
  margin: { top: "18mm", bottom: "20mm", left: "20mm", right: "20mm" } });
await browser.close(); srv.close();

// ---- inspection
const bytes = fs.statSync(out).size;
if (fs.readFileSync(out).subarray(0, 5).toString() !== "%PDF-" || bytes < 200000) fail("not a PDF or suspiciously small");
const info = execFileSync("pdfinfo", [out]).toString();
const pages = Number((info.match(/^Pages:\s+(\d+)/m) || [])[1]);
if (!pages) fail("pdfinfo reports no pages");
const text = execFileSync("pdftotext", ["-layout", out, "-"], { maxBuffer: 1 << 28 }).toString();
const flat = text.replace(/\s+/g, " ");
if (text.includes("�")) fail("extracted text contains U+FFFD (a glyph could not be mapped)");
if (!flat.includes(`content ${build.content_version}`) && !flat.includes(build.content_version)) fail(`content version ${build.content_version} not found in the PDF`);
const strip = (s) => s.replace(/\$[^$]*\$/g, "").replace(/[*_`]/g, "").replace(/\s+/g, " ").trim();
const missing = [];
for (const f of fs.readdirSync(path.resolve("content", "chapters"))) {
  const t = (fs.readFileSync(path.resolve("content", "chapters", f), "utf8").match(/^title:\s*"?(.*?)"?$/m) || [])[1] || "";
  const probe = strip(t).split(" ").filter((w) => /^[A-Za-z]{4,}$/.test(w)).slice(0, 3).join(" ");
  if (probe && !flat.includes(probe)) missing.push(`${f}: «${probe}»`);
}
if (!flat.includes("Bibliography")) missing.push("Bibliography");
if (missing.length) fail(`chapter titles not found in the extracted text:\n  ${missing.join("\n  ")}`);
const fonts = execFileSync("pdffonts", [out]).toString().split("\n").slice(2).filter(Boolean);
const unembedded = fonts.filter((l) => / no\s+(yes|no)\s+(yes|no)\s+\d+\s+\d+\s*$/.test(l));
if (unembedded.length) fail(`fonts not embedded:\n  ${unembedded.join("\n  ")}`);

// ---- publish
const pub = path.resolve("site", "downloads");
fs.mkdirSync(pub, { recursive: true });
fs.copyFileSync(out, path.join(pub, FILE));
const sha = crypto.createHash("sha256").update(fs.readFileSync(out)).digest("hex");
const words = flat.split(" ").length;
const manifest = { file: FILE, pages, bytes, sha256: sha, content_version: build.content_version, source_build: build.build, words_extracted: words,
  fonts: fonts.length, generated: new Date().toISOString().slice(0, 10), generator: "book/tools/pdf.mjs (Chromium print of dist/print.html)",
  checks: ["width", "pdf-header", "pdfinfo-pages", "chapter-titles", "no-U+FFFD", "fonts-embedded", "content-version"] };
fs.writeFileSync(path.join(pub, "pdf.json"), JSON.stringify(manifest, null, 1) + "\n");
console.log(`wrote ${FILE}: ${pages} pages, ${(bytes / 1e6).toFixed(1)} MB, ${words} words extracted, ${fonts.length} fonts (all embedded), content ${build.content_version}`);
